# Generated by Django 3.1.6 on 2021-02-04 10:34

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress1',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='adress2',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='package_choice',
            field=models.CharField(choices=[('PDOS', 'Pack Dossier'), ('PVST', 'Pack Visite'), ('PBAS', 'Pack Basique'), ('PBST', 'Pack Booster'), ('PPRE', 'Pack Premium'), ('PCNC', 'Pack Conciergerie')], default='PDOS', max_length=4),
        ),
        migrations.AddField(
            model_name='client',
            name='personne_foyer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
