# Generated by Django 3.1.6 on 2021-02-04 10:46

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('client', '0002_auto_20210204_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adress2',
            new_name='address2',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='address.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='address.address'),
        ),
    ]
