# Generated by Django 3.1.6 on 2021-02-04 11:45

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('client', '0007_auto_20210204_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='address.address'),
        ),
    ]
