# Generated by Django 3.1.6 on 2021-02-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20210204_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='situation_matrimo',
            field=models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4),
        ),
    ]
