# Generated by Django 3.1.6 on 2021-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20210204_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='SalaireFoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='budgetLoyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='situation_matrimo',
            field=models.CharField(choices=[('MARR', 'Marrié (e)'), ('DIVO', 'Divorcé (e)'), ('CELI', 'Célibataire'), ('SEPA', 'Séparé (e)'), ('VEUF', 'Veuf (ve)')], default='CELI', max_length=4, verbose_name='Situation matrimoniale'),
        ),
    ]
