# Generated by Django 3.1.6 on 2021-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210204_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_avis',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail"),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_paye',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name="Pièce 2: 3 dernières fiches de payes, pièces d'identité"),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_quittance',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Pièce 3: 3 dernières quittance de loyers'),
        ),
    ]
