# Generated by Django 3.1.6 on 2021-03-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0028_auto_20210331_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressannonce',
            old_name='account',
            new_name='annonce',
        ),
    ]
