# Generated by Django 3.1.6 on 2021-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0029_auto_20210331_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='dureeLocationMaxi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='dureeLocationMini',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
