# Generated by Django 2.2 on 2020-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcli',
            name='cli_referent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
