# Generated by Django 3.1.4 on 2021-01-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0002_clientcli_cli_referent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcli',
            name='cli_referent',
            field=models.CharField(max_length=100, null=True, verbose_name='Referent'),
        ),
    ]
