# Generated by Django 3.1.4 on 2021-01-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0003_auto_20210104_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignerCli',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('cli_prenom', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('cli_email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('cli_document_avis', models.FileField(null=True, upload_to='documents/', verbose_name="Pièce 1: Avis d'impot, attestation d'emplyeur ou contrat de travail")),
            ],
            options={
                'verbose_name': 'SignerClient',
                'db_table': 'Signer_Cli',
                'managed': True,
            },
        ),
    ]
