# Generated by Django 3.1.4 on 2021-01-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0005_checkboxcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkboxcourse1',
            fields=[
                ('cb1_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename1', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'check box courses',
                'db_table': 'CheckBox1_Cli',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clientcli',
            name='cli_checkbox',
            field=models.ManyToManyField(to='soumission.checkboxcourse1', verbose_name='Signer et Accepter les conditions'),
        ),
    ]
